Add missing dependency for new GUI test
https://travis-ci.org/bleachbit/bleachbit/jobs/653971931#L1052

======================================================================
ERROR: test_notify (tests.TestGUI.GUITestCase)
Test a pop-up notification
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/bleachbit/bleachbit/tests/TestGUI.py", line 187, in test_notify
    notify('This is a test notification')
  File "/home/travis/build/bleachbit/bleachbit/bleachbit/GUI.py", line 110, in notify
    notify_gi(msg)
  File "/home/travis/build/bleachbit/bleachbit/bleachbit/GUI.py", line 64, in notify_gi
    gi.require_version('Notify', '0.7')
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available