Fix error with walk.top when top directory does not exist
Error: internet_explorer.cache: Command to delete C:\Users\username\Ustawienia lokalne\WebCache.old
Traceback (most recent call last):
  File "\bleachbit\Worker.py", line 88, in execute
    for ret in cmd.execute(self.really_delete):
  File "\bleachbit\Command.py", line 81, in execute
    'size': FileUtilities.getsize(self.path)}
  File "\bleachbit\FileUtilities.py", line 438, in getsize
    finddata = win32file.FindFilesW(extended_path(path))